### ISSUE TITLE
Couldn't install on MacOS

### ISSUE THREAD

**Issue by izxle** [loenard97/hdf5-viewer#1]
I tried to build the binary:

```sh
$ python pyinstaller.py
1696 INFO: PyInstaller: 5.10.0
1696 INFO: Python: 3.11.7 (conda)
1737 INFO: Platform: macOS-10.16-x86_64-i386-64bit
1738 INFO: wrote hdf5-viewer/main.spec
1742 INFO: UPX is not available.
1744 INFO: Extending PYTHONPATH with paths
['hdf5-viewer']
9383 INFO: Appending 'datas' from .spec
9384 INFO: checking Analysis
9384 INFO: Building Analysis because Analysis-00.toc is non existent
9384 INFO: Initializing module dependency graph...
9387 INFO: Caching module graph hooks...
9400 INFO: Analyzing base_library.zip ...
11777 INFO: Loading module hook 'hook-heapq.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
11867 INFO: Loading module hook 'hook-encodings.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
13833 INFO: Loading module hook 'hook-pickle.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
15366 INFO: Caching module dependency graph...
15483 INFO: running Analysis Analysis-00.toc
15491 INFO: Analyzing hdf5-viewer/main.py
15556 INFO: Loading module hook 'hook-platform.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
15590 INFO: Loading module hook 'hook-xml.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
15668 INFO: Loading module hook 'hook-h5py.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
15683 INFO: Loading module hook 'hook-numpy.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/numpy/_pyinstaller'...
15729 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
16330 INFO: Loading module hook 'hook-difflib.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
16514 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
17517 INFO: Loading module hook 'hook-sysconfig.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
18676 INFO: Loading module hook 'hook-pyqtgraph.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5179 WARNING: Failed to collect submodules for 'pyqtgraph.opengl' because importing 'pyqtgraph.opengl' raised: ModuleNotFoundError: No module named 'OpenGL'
24361 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
24384 INFO: Loading module hook 'hook-PyQt6.uic.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
24485 INFO: Loading module hook 'hook-PyQt6.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
25591 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
26517 INFO: Processing module hooks...
26518 WARNING: Hidden import "six" not found!
26816 INFO: Loading module hook 'hook-PyQt6.QtWidgets.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
26876 INFO: Loading module hook 'hook-PyQt6.QtTest.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
26943 INFO: Loading module hook 'hook-PyQt6.QtGui.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27018 INFO: Loading module hook 'hook-PyQt6.QtCore.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27093 INFO: Loading module hook 'hook-PyQt6.QtSvg.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27179 INFO: Loading module hook 'hook-PyQt6.QtOpenGLWidgets.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27245 INFO: Loading module hook 'hook-PyQt6.QtOpenGL.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27313 INFO: Loading module hook 'hook-PyQt6.QtDBus.py' from 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks'...
27399 INFO: Looking for ctypes DLLs
27442 INFO: Analyzing run-time hooks ...
27450 INFO: Including run-time hook 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
27453 INFO: Including run-time hook 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
27456 INFO: Including run-time hook 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
27460 INFO: Including run-time hook 'miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt6.py'
27462 INFO: Including run-time hook 'miniconda3/envs/h5/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pyqtgraph_multiprocess.py'
27477 INFO: Looking for dynamic libraries
miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/build_main.py:177: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
29413 INFO: Looking for eggs
29413 INFO: Python library not among binary dependencies. Performing additional search...
29419 INFO: Using Python library miniconda3/envs/h5/lib/libpython3.11.dylib
29430 INFO: Warnings written to hdf5-viewer/build/main/warn-main.txt
29479 INFO: Graph cross-reference written to hdf5-viewer/build/main/xref-main.html
29508 INFO: checking PYZ
29508 INFO: Building PYZ because PYZ-00.toc is non existent
29508 INFO: Building PYZ (ZlibArchive) hdf5-viewer/build/main/PYZ-00.pyz
30164 INFO: Building PYZ (ZlibArchive) hdf5-viewer/build/main/PYZ-00.pyz completed successfully.
30172 INFO: EXE target arch: x86_64
30172 INFO: Code signing identity: None
30173 INFO: checking PKG
30173 INFO: Building PKG because PKG-00.toc is non existent
30173 INFO: Building PKG (CArchive) main.pkg
30192 INFO: Building PKG (CArchive) main.pkg completed successfully.
30193 INFO: Bootloader miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
30193 INFO: checking EXE
30193 INFO: Building EXE because EXE-00.toc is non existent
30193 INFO: Building EXE from EXE-00.toc
30193 INFO: Copying bootloader EXE to hdf5-viewer/build/main/main
30199 INFO: Converting EXE to target arch (x86_64)
30459 INFO: Removing signature(s) from EXE
30482 INFO: Appending PKG archive to EXE
30490 INFO: Fixing EXE headers for code signing
30509 INFO: Rewriting the executable's macOS SDK version (12.1.0) to match the SDK version of the Python library (10.14.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
30510 INFO: Re-signing the EXE
30559 INFO: Building EXE from EXE-00.toc completed successfully.
30561 INFO: checking COLLECT
30562 INFO: Building COLLECT because COLLECT-00.toc is non existent
30562 INFO: Building COLLECT COLLECT-00.toc
37882 INFO: Building COLLECT COLLECT-00.toc completed successfully.
37887 INFO: checking BUNDLE
37887 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
37887 INFO: Building BUNDLE BUNDLE-00.toc
Traceback (most recent call last):
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/icon.py", line 50, in normalize_icon_type
    from PIL import Image as PILImage
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hdf5-viewer/pyinstaller.py", line 42, in <module>
    build()
  File "hdf5-viewer/pyinstaller.py", line 27, in build
    PyInstaller.__main__.run(
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 978, in main
    build(specfile, distpath, workpath, clean_build)
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 900, in build
    exec(code, spec_namespace)
  File "hdf5-viewer/main.spec", line 52, in <module>
    app = BUNDLE(
          ^^^^^^^
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/osx.py", line 112, in __init__
    self.__postinit__()
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/osx.py", line 137, in assemble
    self.icon = normalize_icon_type(self.icon, ("icns",), "icns", CONF["workpath"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/icon.py", line 54, in normalize_icon_type
    raise ValueError(
ValueError: Received icon image 'hdf5-viewer/src/img/file.svg' which exists but is not in the correct format. On this platform, only ('icns',) images may be used as icons. If Pillow is installed, automatic conversion will be attempted. Please install Pillow or convert your 'svg' file to one of ('icns',) and try again.

```

I then installed pillow and tried to build again:

```sh
$ python pyinstaller
953 INFO: PyInstaller: 5.10.0
953 INFO: Python: 3.11.7 (conda)
1002 INFO: Platform: macOS-10.16-x86_64-i386-64bit
1003 INFO: wrote hdf5-viewer/main.spec
1007 INFO: UPX is not available.
1008 INFO: Extending PYTHONPATH with paths
['hdf5-viewer']
1334 INFO: Appending 'datas' from .spec
1336 INFO: checking Analysis
1356 INFO: checking PYZ
1367 INFO: EXE target arch: x86_64
1367 INFO: Code signing identity: None
1367 INFO: checking PKG
1368 INFO: Bootloader miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
1369 INFO: checking EXE
1370 INFO: checking COLLECT
1372 INFO: Removing dir hdf5-viewer/dist/main
1405 INFO: Building COLLECT COLLECT-00.toc
3951 INFO: Building COLLECT COLLECT-00.toc completed successfully.
3956 INFO: checking BUNDLE
3956 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
3957 INFO: Removing dir hdf5-viewer/dist/main.app
3957 INFO: Building BUNDLE BUNDLE-00.toc
Traceback (most recent call last):
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/icon.py", line 65, in normalize_icon_type
    with PILImage.open(icon_path) as im:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'hdf5-viewer/src/img/file.svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hdf5-viewer/pyinstaller.py", line 42, in <module>
    build()
  File "hdf5-viewer/pyinstaller.py", line 27, in build
    PyInstaller.__main__.run(
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 978, in main
    build(specfile, distpath, workpath, clean_build)
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 900, in build
    exec(code, spec_namespace)
  File "hdf5-viewer/main.spec", line 52, in <module>
    app = BUNDLE(
          ^^^^^^^
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/osx.py", line 112, in __init__
    self.__postinit__()
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/osx.py", line 137, in assemble
    self.icon = normalize_icon_type(self.icon, ("icns",), "icns", CONF["workpath"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/h5/lib/python3.11/site-packages/PyInstaller/building/icon.py", line 69, in normalize_icon_type
    raise ValueError(
ValueError: Something went wrong converting icon image 'hdf5-viewer/src/img/file.svg' to '.icns' with Pillow, perhaps the image format is unsupported. Try again with a different file or use a file that can be used without conversion on this platform: ('icns',)
```

I also tried to pip install just in case:

```sh
$ pip install -e .
Obtaining hdf5-viewer
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running egg_info
      writing src/hdf5viewer.egg-info/PKG-INFO
      writing dependency_links to src/hdf5viewer.egg-info/dependency_links.txt
      writing requirements to src/hdf5viewer.egg-info/requires.txt
      writing top-level names to src/hdf5viewer.egg-info/top_level.txt
      error: package directory 'src/hdf5viewer' does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by loenard97** [comment]
Seems like two different issues:
 1. Pyinstaller can't find an icon on MacOS. I changed the Pyinstaller script to only search for icons on Windows.
 2. I changed the folder structure some time ago, but forgot to change the README. `pip install -e .` is not necessary any more. I updated the README accordingly.
 
 Could you pull the latest commit and try again?

 It's a bit difficult for me to support MacOS, because I don't have a Mac and I have never used MacOS before. But let me know if it works or not and I can have another look if you get a different error message now.

**Comment by sun-rongyang** [comment]
@loenard97 Thank you very much for making this nice tool! I have tried v0.2.0 on MacOS. It can work.
